require_relative './config/environment'
require 'sinatra/activerecord/rake'

desc "Runs a Pry console"
task :console do
  # This line turns on logging of the SQL generated by Active Record
  ActiveRecord::Base.logger = Logger.new(STDOUT)
  
  # Open a Pry session
  Pry.start
end


describe "#characters" do
  it "returns the characters associated with the show" do
    simpsons = Show.create(name: "The Simpsons")
    Character.create(name: "Ralph Wiggum", show_id: simpsons.id)
    Character.create(name: "Homer Simpson", show_id: simpsons.id)
    Character.create(name: "Apu Nahasapeemapetilon", show_id: simpsons.id)
    expect(simpsons.characters.count).to eq(3)
  end

  it "can be used to build its characters" do
    show = Show.create(name: "Happy Endings")
    show.characters.build(name: "Penny")
    show.save
    expect(show.characters.count).to eq(1)
  end
end
